name: Deploy GH Pages

on: push

defaults:
  run:
    working-directory: app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: yarn
        working-directory: app

      - name: Build
        run: yarn build
        working-directory: app

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: main
          folder: ./app/build
